
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Deploy to Amazon EC2

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python environment # setting python environment to 3.x
      run: source ~/venv/bin/activate && pip install -r requirements.txt
    
    - name: run migrations   
      run: source ~/venv/bin/activate && python manage.py makemigrations && python manage.py migrate
    - name: Restart daemon
      run: sudo systemctl daemon-reload
    - name: Restart gunicorn
      run: sudo systemctl restart gunicorn
    - name: Restart nginx 
      run: sudo systemctl restart nginx
 


 
